version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: resetbiology_woo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - woo_network

  # WordPress + WooCommerce
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: resetbiology_woo_wp
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - woo_network

  # WP-CLI for automation
  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    container_name: resetbiology_woo_cli
    user: "33:33"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - woo_network
    command: tail -f /dev/null

volumes:
  db_data:

networks:
  woo_network:
    driver: bridge
