import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync(new URL('../src/components/PitchDefender/PitchforksIII.tsx', import.meta.url), 'utf8')
const playStart = source.indexOf('data-testid="pf3-learning-dock"')
const playEnd = source.indexOf('{geometryDebug && (', playStart)
assert.ok(playStart >= 0 && playEnd > playStart, 'playing learning dock must exist')
const dock = source.slice(playStart, playEnd)

assert.match(source, /type PortraitDockPanel = 'staff' \| 'settings' \| null/)
assert.doesNotMatch(source, /pointer-events-none absolute bottom-2 left-1\/2[^\n]*pf3-portrait-staff/)
assert.ok(dock.indexOf('pf3-portrait-staff-band') > dock.indexOf('pf3-learning-dock'), 'portrait staff must live inside the dock')
assert.match(dock, /data-testid="pf3-replay-notes"[\s\S]*?min-h-12/)
assert.match(dock, /data-testid="pf3-staff-drawer-toggle"[\s\S]*?aria-expanded=\{portraitDockPanel === 'staff'\}[\s\S]*?min-h-12/)
assert.match(dock, /data-testid="pf3-options-drawer-toggle"[\s\S]*?aria-expanded=\{portraitDockPanel === 'settings'\}[\s\S]*?min-h-12/)
assert.match(dock, /id="pf3-portrait-staff-panel"[\s\S]*?role="region"[\s\S]*?aria-label="Staff notation drawer"/)
assert.match(dock, /id="pf3-portrait-options-panel"[\s\S]*?max-h-\[30svh\][\s\S]*?overflow-y-auto overscroll-contain/)
assert.match(dock, /\{portraitDockPanel === 'settings' && \(/, 'settings are opt-in on desktop as well as phone')
assert.doesNotMatch(dock, /layoutMode !== 'portrait' \|\| portraitDockPanel === 'settings'/, 'desktop must not reopen the always-visible settings that squeeze the battlefield')
assert.match(dock, /grid-cols-2 gap-2" data-testid="pf3-ability-dock"/, 'phones keep both ability controls in a stable two-column tray')
assert.match(dock, /data-testid="pf3-close-smash-action"[\s\S]*?min-h-12 min-w-\[48px\]/, 'close smash keeps a 48px touch target')
assert.match(dock, /data-testid="pf3-raincall-action"[\s\S]*?min-h-12/, 'raincall keeps a 48px touch target')
assert.match(dock, /data-testid="pf3-options-scroll-cue"[\s\S]*?SCROLL FOR MORE OPTIONS/, 'options expose a visible scroll affordance')
assert.match(dock, /if \(layoutMode === 'portrait' && value\) setPortraitDockPanel\('staff'\)/)
assert.match(dock, /touchSized=\{layoutMode === 'portrait'\}/)
assert.match(source, /const controlSize = props\.touchSized \? 'min-h-12' : ''/)
assert.match(source, /Math\.min\(containerWidth - 32, 360\)/)
assert.match(source, /const STAGE_MIN_HEIGHT_VW = \(H \/ W\) \* 100/)
assert.match(source, /const STAGE_MIN_HEIGHT_CSS = `min\(\$\{H\}px, \$\{STAGE_MIN_HEIGHT_VW\}vw\)`/)
assert.match(source, /fixed inset-0 overflow-y-auto overflow-x-hidden/, 'short stages must scroll vertically instead of clipping the playing surface')
assert.match(source, /data-testid="pf3-stage"[\s\S]*?style=\{\{ minHeight: STAGE_MIN_HEIGHT_CSS \}\}/, 'the battlefield keeps a width-derived 16:9 minimum')
assert.match(source, /staffNotationVisible: inputMode === 'buttons' \? false : staffNotationRef\.current && layoutModeRef\.current !== 'portrait'/)
assert.match(source, /layoutModeRef\.current === 'portrait' &&[\s\S]*?inputModeRef\.current !== 'buttons' &&[\s\S]*?staffNotationRef\.current &&[\s\S]*?view\.tuner\.visible[\s\S]*?drawStaffNotationView\(staffCtx, view\)/)
assert.doesNotMatch(source, /layoutModeRef\.current === 'portrait' && view\.staffNotationVisible/)

console.log('pitchforks responsive learning dock: PASS (26 source assertions; browser geometry checked separately)')
