// AUTO-GENERATED by scripts/loupe/sync-peptide-cards-to-rb.mjs in jarvis repo.
// DO NOT EDIT BY HAND. Re-run sync to refresh.

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

export type ExpertBaseline = {
  source: string;
  source_pdf?: string;
  purpose: string;
  vial_mg: string;
  bac_mL: string;
  dose: string;
  units_on_1mL_insulin: string;
  timing: string;
  frequency: string;
  duration: string;
};

export type ExpertSummary = {
  mention_count: number;
  top_doses: { dose: string; count: number }[];
  top_sources: {
    source_id: string | null;
    source_type: 'podcast' | 'email';
    source_title: string | null;
    source_date: string | null;
    source_url: string | null;
    mention_count: number;
    top_snippet: string;
    top_context: string;
    first_timestamp: string | null;
  }[];
  acute_signals: { snippet: string; source_title: string | null; source_date: string | null; timestamp: string | null; source_url: string | null }[];
  chronic_signals: { snippet: string; source_title: string | null; source_date: string | null; timestamp: string | null; source_url: string | null }[];
};

export type PeptideCard = {
  peptide: string;
  slug: string;
  category: string;
  aliases: string[];
  experts: {
    'hunter-williams'?: { baseline_protocol: ExpertBaseline | null; summary: ExpertSummary };
    'taylor-williams'?: { summary: ExpertSummary; female_specific_note: string };
    'trevor-bachmeyer'?: { summary: ExpertSummary; acute_vs_chronic_note: string };
  };
  reset_biology_synthesis: {
    status: string;
    recommendation: string | null;
    caveats: string | null;
    cross_expert_consensus: string | null;
    cross_expert_disagreement: string | null;
  };
  generated_at: string;
};

export type PeptideIndexEntry = {
  slug: string;
  peptide: string;
  category: string;
  aliases: string[];
  total_mentions: number;
  has_hunter_baseline: boolean;
  has_taylor: boolean;
  has_bachmeyer: boolean;
};

const DATA_DIR = join(process.cwd(), 'src/data/peptide-education');

let _index: PeptideIndexEntry[] | null = null;
export function peptideIndex(): PeptideIndexEntry[] {
  if (_index) return _index;
  _index = JSON.parse(readFileSync(join(DATA_DIR, 'index.json'), 'utf8'));
  return _index!;
}

export function getPeptide(slug: string): PeptideCard | null {
  const path = join(DATA_DIR, `${slug}.json`);
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

export function listPeptideSlugs(): string[] {
  return readdirSync(DATA_DIR)
    .filter(f => f.endsWith('.json') && f !== 'index.json')
    .map(f => f.replace(/\.json$/, ''));
}
